### PR TITLE
fix signage display ratio

### PR DESCRIPTION
**Pull request by tkhmy**
Signed-off-by: khtan <tkh.my.p@gmail.com>

## Description(required)
- fix signage small volume 

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write release notes

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yabuta** [comment]
@tkhmy 最初の走行だけ文字がかぶることがあったのですがこれはなぜかわかりますか？

Screenshot from 2022-11-04 13-30-14

Screenshot from 2022-11-04 13-33-58

**Comment by tkhmy** [comment]
> @tkhmy 最初の走行だけ文字がかぶることがあったのですがこれはなぜかわかりますか？
> 
> Screenshot from 2022-11-04 13-30-14
> 
> Screenshot from 2022-11-04 13-33-58

@yabuta 多分サイズまだ合わないですね、調整します。

**Comment by yabuta** [comment]
@tkhmy dev環境の西新宿の地図で確認できますがタンさんの方で確認が難しければこちらで確認します

**Comment by tkhmy** [comment]
> @tkhmy dev環境の西新宿の地図で確認できますがタンさんの方で確認が難しければこちらで確認します

@yabuta すみません、今修正しましたので、確認お願いできますか？

**Review by yabuta — APPROVED** [review]
LGTM

**Pull request merged**
